config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  resources :users, except: [:new] do
    delete 'logout', :on => :collection
    get 'profile', :on => :member
  end

  resources :posts, except: [:new, :index]

  resources :comments, except: [:new, :index]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user

  def current_user
 		if session[:user_id]
  	  @current_user = User.find(session[:user_id])
 	 	end
	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(user_id: current_user.id, post_id: params[:comment][:id], combody: params[:comment][:combody])
    flash[:notice] = "Your comment has been added to the post!"
    redirect_to post_path(params[:comment][:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Your comment has been deleted"
    redirect_to post_path(@comment.post.id)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def show
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(combody: params[:comment][:combody])
    flash[:notice] = "Your comment is successfully Updated."
    redirect_to post_path(@comment.post.id)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    Post.create(user_id: current_user.id, title: params[:title], body: params[:body])
    flash[:notice] = "Your post has been added to the feed!"
    redirect_to user_path(current_user)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Your post has been deleted"
    redirect_to user_path(current_user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @users = User.all
    @comments = Comment.all
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    flash[:notice] = "Your post is successfully Updated."
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    if params[:password] == params[:password2]
      @user = User.create(username: params[:username], email: params[:email], password: params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "You are signed up and good to go, Welcome!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Please make sure your passwords match."
      redirect_to users_path
    end
  end

  def destroy
    @user = current_user  
    @user.destroy
    session.clear
    flash[:notice] = "Your account has been deleted"
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @user = User.where(email: params[:email]).first
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      flash[:notice] = "You've been signed in successfully."
      redirect_to user_path(current_user.id)
    elsif params[:email] || params[:password]
      flash[:alert] = "Invalid E-mail or Password, please Sign-up or try again."
    end
    @users = User.all
    @posts = Post.all
    @comments = Comment.all
  end

  def show
    @users = User.find(params[:id])
    @user = current_user
    @posts = Post.all
    @comments = Comment.all
  end

  def update
    @user = User.find(params[:id])
    if user_params[:password] == user_params[:password2]
      @user.update(euser_params)
      flash[:notice] = "Your Info is successfully Updated."
      redirect_to user_path(@user)
    else flash[:alert] = "Your PASSWORDS do not match!."
      redirect_to edit_user_path(@user)
    end
  end

  def logout
    session.clear
    flash[:notice] = "You are Logged off."
    redirect_to users_path
  end

  def profile
    @users = User.find(params[:id])
    @posts = Post.all
    @comments = Comment.all
    redirect_to(user_path) if current_user != nil && current_user.id == @users.id
  end

  private

  def user_params
    params.require(:user).permit(:password, :password2)
  end

  def euser_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<nav>
  <div class="navlink">
    <a href="/">Home</a>
  </div>
  <div class="navlink">
    <a href="/users/<%=current_user.id%>">My Profile</a>
  </div>
  <div id="logout">
    <%= button_to("Log Out", logout_users_path, method: :delete) %>
  </div>
</nav>

<div id="edit">
	<center>
		<%= form_for @comment do |f| %>
			<br>
			<h4><%= f.label "Edit comment: " %></h4>
		  <br>
		  <%= f.text_area :combody, cols: "50", rows: "4" %>
		  <br>
		  <%= f.hidden_field :id, value: @comment.id %>
		  <%= f.submit "Update" %>
		<% end %>
		<br>
		Delete your comment:
		<%= button_to("Delete", comment_path(@comment.id), method: :delete, data: {confirm: "Your comment will be DELETED, ok?"}) %>
	</center>
</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>¿Whos Blog? Jay Hu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="flash">
    <center>
    	<% if flash[:notice] %>
        <div class="flash notice">
          <%=flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="flash alert">
          <%=flash[:alert] %>
        </div>
      <% end %>
    </center>
  </div>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<nav>
  <div class="navlink">
    <a href="/">Home</a>
  </div>
  <div class="navlink">
    <a href="/users/<%=current_user.id%>">My Profile</a>
  </div>
  <div id="logout">
    <%= button_to("Log Out", logout_users_path, method: :delete) %>
  </div>
</nav>

<div id="edit">
	<center>
		<br>
		<h4>Edit:</h4>
		<br>
		<%= form_for @post do |f| %>
		  <%= f.label "Title: " %>
		  <br>
		  <%= f.text_area :title, cols: "50", rows: "1" %>
		  <br>
		  <%= f.label "Body: " %>
		  <br>
		  <%= f.text_area :body, cols: "50", rows: "4" %>
		  <br>
		  <%= f.submit "Update" %>
		<% end %>
		<br>
		Delete your post:
		<%= button_to("Delete", post_path(@post.id), method: :delete, data: {confirm: "Your post will be DELETED, ok?"}) %>
		<br>
	</center>
</div>

app/views/posts/show.html.erb
<% if current_user == nil %>

  <nav>
    <a class="navlink" href="/">Home</a>
    <div id="login">
      <b>Login:</b>
      <%= form_tag("/users", action: "index", method: "get")do %>
        <%= label_tag "E-mail: " %>
        <%= email_field_tag :email %>
        <%= label_tag "Password: " %>
        <%= password_field_tag :password %>
        <%= submit_tag "Log in" %>
      <% end %>
    </div>
  </nav>

<% end %>

<% if current_user != nil %>

  <nav>
    <div class="navlink">
      <a href="/">Home</a>
    </div>
    <div class="navlink">
      <a href="/users/<%=current_user.id%>">My Profile</a>
    </div>
    <div id="logout">
      <%= button_to("Log Out", logout_users_path, method: :delete) %>
    </div>
  </nav>

<% end %>

<div id="feed">
  <div id="right">
    <h1><%= @post.title %></h1>
    Posted <%= distance_of_time_in_words(Time.now, @post.created_at) %>
    <br>
    by: <a href="/users/<%=@post.user.id%>/profile">
          <%= @post.user.username %>
        </a>

    <% if current_user != nil && current_user.id == @post.user.id %>
       | <%= link_to("Delete", post_path(@post.id), method: :delete, data: {confirm: "Your post will be DELETED, ok?"}) %> | <%= link_to("Edit", edit_post_path(@post.id), method: :get) %>
    <% end %>

    <br>
    <br>
    <%= @post.body %>
    <br>
    <br>
  </div>

  <div id="left">  
    <h4>Comments: </h4>

    <% @post.comments.each do |comment| %>
      <br>
      <%= comment.combody %>
      <br>
      Posted <%= distance_of_time_in_words(Time.now, comment.created_at) %> 
      by: <a href="/users/<%=comment.user.id%>/profile">
            <%= comment.user.username %> 
          </a>

      <% if current_user != nil && current_user.id == comment.user.id %>
         | <%= link_to("Delete", comment_path(comment.id), method: :delete, data: {confirm: "Your comment will be DELETED, ok?"}) %> | <%= link_to("Edit", edit_comment_path(comment.id), method: :get) %>
      <% end %>

      <br>
      <hr>
    <% end %>

    <% if current_user != nil %>

      <%= form_for Comment.new do |f| %>
        <br>
        <h4><%= f.label "Would you like to post a comment: " %></h4>
        <br>
        <%= f.text_area :combody, size: "50x4" %>
        <br>
        <%= f.hidden_field :id, value: @post.id %>
        <%= f.submit "Submit" %>
      <% end %>
  </div>
</div>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/edit.html.erb
<nav>
  <div class="navlink">
    <a href="/">Home</a>
  </div>
  <div class="navlink">
    <a href="/users/<%=current_user.id%>">My Profile</a>
  </div>
  <div id="logout">
    <%= button_to("Log Out", logout_users_path, method: :delete) %>
  </div>
</nav>

<div id="edit">
  <center>
    <br>
    <h4>Edit:</h4>
    <%= form_for @user do |f| %>
    	<br>
      <%= f.label "E-mail: " %>
      <br>
      <%= f.email_field :email %>
      <br>
      <%= f.label "Username: " %>
      <br>
      <%= f.text_field :username %>
      <br>
      <%= f.label "Password: " %>
      <br>
      <%= f.password_field :password %>
      <br>
      <%= f.label "Re-type Password: " %>
      <br>
      <%= f.password_field :password2 %>
      <br>
      <br>
      <%= f.submit "Update" %>
    <% end %>
    <br>
    Delete your account: 
    <%= button_to("Delete", user_path(current_user.id), method: :delete, data: {confirm: "Your account will be DELETED, ok?"}) %>
    <br>
  </center>
</div>

app/views/users/index.html.erb
<% if current_user == nil %>

<nav>
  <a class="navlink" href="/">Home</a>
  <div id="login">
    <b>Login:</b>
    <%= form_tag("/users", action: "index", method: "get")do %>
      <%= label_tag "E-mail: " %>
      <%= email_field_tag :email %>
      <%= label_tag "Password: " %>
      <%= password_field_tag :password %>
      <%= submit_tag "Log in" %>
    <% end %>
  </div>
</nav>

  <div id="logoff">
    <div id="logo">
      <h1>¿Whos Blog?</h1>
    </div>

    <div id="signup">
      <center><h2>Sign-up:</h2></center>
      <%= form_tag("/users")do %>
        <%= label_tag "E-mail: " %>
        <br>
        <%= email_field_tag :email %>
        <br>
        <%= label_tag "Username: " %>
        <br>
        <%= text_field_tag :username %>
        <br>
        <%= label_tag "Password: " %>
        <br>
        <%= password_field_tag :password %>
        <br>
        <%= label_tag "Re-type Password: " %>
        <br>
        <%= password_field_tag :password2 %>
        <br>
        <center><%= submit_tag "Submit" %></center>
      <% end %>
    </div>
  </div>

<% end %>

<% if current_user != nil %>

  <nav>
    <div class="navlink">
      <a href="/">Home</a>
    </div>
    <div class="navlink">
      <a href="/users/<%=current_user.id%>">My Profile</a>
    </div>
    <div id="logout">
      <%= button_to("Log Out", logout_users_path, method: :delete) %>
    </div>
  </nav>

  <div id="divlogo">
    <div id="logo">
      <h1>¿Whos Blog?</h1>
    </div>
  </div>

<% end %>

<div id="feed">
  <center>
    <h1>¿Post Feed?</h1>
  </center>
  <br>
  <% @posts.reverse.each do |post| %>
    <hr>
    <br>
    <div id="content">
      <u>Title</u>: 
      <a href="/posts/<%=post.id%>">
        <%= post.title %>
      </a>
      <br>
      <%= post.body %>
      <br>
      Posted <%= distance_of_time_in_words(Time.now, post.created_at) %>
      <br>
      by: 
      <a href="/users/<%=post.user.id%>/profile">
        <%= post.user.username %>
      </a>
      <% if current_user != nil && current_user.id == post.user.id %> | 
        <%= link_to("Delete", post_path(post.id), method: :delete, data: {confirm: "Your post will be DELETED, ok?"}) %> | 
        <%= link_to("Edit", edit_post_path(post.id), method: :get) %>
      <% end %>
      <br>
      <br>
    </div>
  <% end %>
</div>

app/views/users/profile.html.erb
<% if current_user == nil %>
  Login:
<%= form_tag("/users", action: "index", method: "get")do %>

  <%= label_tag "E-mail: " %>
  <%= email_field_tag :email %>

  <%= label_tag "Password: " %>
  <%= password_field_tag :password %>

  <%= submit_tag "Log in" %>
<% end %>

Sign-up:
<%= form_tag("/users")do %>

  <%= label_tag "E-mail: " %>
  <%= email_field_tag :email %>

  <%= label_tag "Username: " %>
  <%= text_field_tag :username %>

  <%= label_tag "Password: " %>
  <%= password_field_tag :password %>

  <%= label_tag "Re-type Password: " %>
  <%= password_field_tag :password2 %>

  <%= submit_tag "Submit" %>
<% end %>

<% end %>

<% if current_user != nil %>
<%= button_to("Log Out", logout_users_path, method: :delete) %>
<% end %>

<h1><%= @users.username %>'s Profile</h1>
  Member for <%= distance_of_time_in_words(Time.now,  @users.created_at) %>
  <br>
  <b>Contact: </b><%= @users.email %>
  <h3><%= @users.username %>'s post</h3>
  <% @posts.reverse.each do |post| %>
  	<% if post.user == @users %>
  	<br>
    <a href="/posts/<%=post.id%>">
      <%= post.title %>
    </a>
  	<br>
    <%= post.body %>
    <br>
    Posted <%= distance_of_time_in_words(Time.now,  post.created_at) %>
    <br>
  <% end %>
<% end %>

app/views/users/show.html.erb
<nav>
  <div class="navlink">
    <a href="/">Home</a>
  </div>
  <div class="navlink">
    <a href="/users/<%=current_user.id%>">My Profile</a>
  </div>
  <div id="logout">
    <%= button_to("Log Out", logout_users_path, method: :delete) %>
  </div>
</nav>

<div id="feed">

  <div id="right2">
    <h1><center>Welcome <%= current_user.username %></center></h1>
    <br>
    Member for <%= distance_of_time_in_words(Time.now,  current_user.created_at) %>
    <br>
    <b>Contact: </b><%= current_user.email %>
    <%= button_to("Edit", edit_user_path(current_user.id), method: :get) %>
    <br>
    <b>Would you like to write a post?</b>
    <br>
    <%= form_tag("/posts")do %>
      <%= label_tag "Title:" %>
      <br>
      <%= text_area_tag(:title, nil, size: "50x1")%>
      <br>
      <%= label_tag "Body:" %>
      <br>
      <%= text_area_tag(:body, nil, size: "50x4")%>
      <br>
      <%= submit_tag "Post" %>
    <% end %>
  </div>

  <div id="left">
    <h3>Your posts:</h3>
    <% @posts.reverse.each do |post| %>
      <% if post.user == current_user %>
        <a href="/posts/<%=post.id%>">
          <%= post.title %>
        </a>	
      	<br>
        <%= post.body %>
        <br>
      	Posted <%= distance_of_time_in_words(Time.now,  post.created_at) %> | <%= link_to("Delete", post_path(post.id), method: :delete, data: {confirm: "Your post will be DELETED, ok?"}) %> | <%= link_to("Edit", edit_post_path(post.id), method: :get) %>
        <br>
        <br>
      <% end %>
    <% end %>
  </div>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>